status-response: "ok"
server:
  ssl: true
  jks-path: C:/Program Files/Java/jdk-17.0.2/lib/security/pbscert
  jks-password: changeit
  http:
    port: 8080
datacenter-region: ams
external-url: https://prebid-server.local
adapters:
  rtbhouse:
    enabled: true
    pbs-enforces-ccpa: false
    endpoint-compression: gzip
    endpoint:  https://prebidserver-s2s-ams.creativecdn.com/bidder/prebidserver/bids
    usersync:
      cookie-family-name: rtbhouse
      redirect:
        url: https://creativecdn.com/cm-notify?pi=prebid-brops&gdpr={{gdpr}}&gdpr_consent={{gdpr_consent}}&us_privacy={{us_privacy}}
        support-cors: false
metrics:
  prefix: prebid
cache:
  scheme: http
  host: localhost
  path: /cache
  query: uuid=
settings:
  enforce-valid-account: false
  generate-storedrequest-bidrequest-id: true
  filesystem:
    settings-filename: sample/sample-app-settings.yaml
    stored-requests-dir: sample/stored
    stored-imps-dir: sample/stored
    stored-responses-dir: sample/stored
    categories-dir:
gdpr:
  default-value: 1
  host-vendor-id: 16
  enabled: true
  vendorlist:
    v2:
      cache-dir: /var/tmp/vendor2
ccpa:
  enforce: false
admin-endpoints:
  logging-changelevel:
    enabled: true
    path: /logging/changelevel
    on-application-port: true
    protected: false
  logging-httpinteraction:
    enabled: true
    path: /logging/httpinteraction
    on-application-port: true
    protected: false
  currency-rates:
    enabled: true
    path: /currency/rates
    on-application-port: false
    protected: false
